# tailscale-auth-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tailscale
  namespace: default
  labels:
    name: k8s-cross-cluster
stringData:
  TS_AUTHKEY: tskey-xxxxxxxxxx  # 由脚本替换为服务端签发的 pre-auth key，手动 kubectl apply -f 的时候亦可手动替换
