# tailscale-extra-args-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-extra-args
  namespace: default
  labels:
    name: k8s-cross-cluster
data:
  TS_EXTRA_ARGS: ""  # 由 --extra-args 参数指定，可传入多个参数（空格分隔）
