package main

import "time"

// CoreDNS configuration constants
const (
	CoreDNSConfigMapName   = "coredns"
	CoreDNSDeploymentName  = "coredns"
	CoreDNSConfigKey       = "Corefile"
	CoreDNSNamespace       = "kube-system"
	ManagedSectionStart    = "### START: Generated by coredns-config-manager - DO NOT EDIT ###"
	ManagedSectionEnd      = "### END: Generated by coredns-config-manager - DO NOT EDIT ###"
)

// Server configuration constants
const (
	syncInterval   = 10 * time.Second
	subdnsPort     = ":10053"
	subdnsIp       = "0.0.0.0"
	subdnsAddr     = subdnsIp + subdnsPort
	metricsPort    = ":8080"
	metricsIp      = "0.0.0.0"
	metricsAddr    = metricsIp + metricsPort
	svcPort        = ":8081"
	svcIp          = "0.0.0.0"
	svcAddr        = svcIp + svcPort
)

// Service discovery configuration constants
const (
	ServiceDiscoveryEndpoint  = "/svc"
	ServiceDiscoveryPort      = 8081
	ServiceDiscoveryTimeout   = 5 * time.Second
)

// Proxy configuration constants
const (
	SOCKS5Proxy          = "127.0.0.1:1055"
	TailscaleProxyService = "tailscale-proxy"
)
