package main

import "time"

const (
	// CoreDNSConfigMapName 是 CoreDNS ConfigMap 的名称
	CoreDNSConfigMapName = "coredns"

	// CoreDNSDeploymentName 是 CoreDNS Deployment 的名称
	CoreDNSDeploymentName = "coredns"

	// CoreDNSConfigKey 是 ConfigMap 中包含 Corefile 的键
	CoreDNSConfigKey = "Corefile"

	// CoreDNSNamespace 是 CoreDNS ConfigMap 所在的命名空间
	CoreDNSNamespace = "kube-system"

	// ManagedSectionStart 是此工具管理的部分的起始标记
	ManagedSectionStart = "### START: Generated by coredns-config-manager - DO NOT EDIT ###"

	// ManagedSectionEnd 是此工具管理的部分的结束标记
	ManagedSectionEnd = "### END: Generated by coredns-config-manager - DO NOT EDIT ###"

	// syncInterval 是主业务循环进行同步的时间间隔，单位为秒
	syncInterval = 10 * time.Second

	// subdnsPort 是子 DNS 服务器监听的端口
	subdnsPort = ":10053"

	// subdnsIp 是子 DNS 服务器监听的IP
	subdnsIp = "0.0.0.0"

	// subdnsAddr 是子 DNS 服务器监听的地址（带端口）
	subdnsAddr = subdnsIp+subdnsPort
)
